### ISSUE TITLE
pm ERR! Cannot read property 'match' of undefined when npm install

### ISSUE THREAD

**Issue by progrish** [AngularExamplesHub/contact-app#1]
![image](https://user-images.githubusercontent.com/14931766/49196668-3807f880-f3a5-11e8-8a0d-b65ebaa88760.png)

**Comment by palashroy** [comment]
Hi progrish, i also got the same issue.

My issue is resolved after **removing "npm-shrinkwrap.json" file** which is not required to restore npm packages.

**Comment by progrish** [comment]
Thank you !! @palashroy  everything is worked!!!
